import { createContext, useContext, useEffect, useMemo, useState } from 'react';
import * as SecureStore from 'expo-secure-store';

const LANGUAGE_KEY = 'appLanguage';

export const AVAILABLE_LANGUAGES = [
  { code: 'en', label: 'English' },
  { code: 'sw', label: 'Kiswahili' },
  { code: 'fr', label: 'Francais' },
  { code: 'es', label: 'Espanol' },
  { code: 'de', label: 'Deutsch' },
  { code: 'zh', label: '中文' },
  { code: 'ar', label: 'العربية' },
];

const translations = {
  en: {
    home: 'Home',
    explore: 'Attractions',
    bookings: 'Bookings',
    chatbot: 'Chatbot',
    profile: 'Profile',
    live: 'Live',
    app_name: 'Explore Kenya',
    welcome_title: 'Discover parks, wildlife, culture, and travel support in one app.',
    welcome_copy:
      'Search attractions, view wildlife information, navigate to destinations, manage bookings, and get travel assistance from the chatbot.',
    traveler: 'Traveler',
    home_hero_title: 'Your Kenya travel hub for stays, sightings, routes, and ready-to-book escapes.',
    home_hero_copy:
      'Start with featured destinations, jump into wildlife learning, ask the assistant for planning help, and move from inspiration to navigation in a few taps.',
    home_ready_label: 'Ready for',
    home_primary_cta: 'Open Explore',
    home_destinations_label: 'Active destinations',
    home_categories_label: 'Spotlight themes',
    home_route_ready_label: 'Route-ready stops',
    home_banner_title: 'Build today\'s adventure faster.',
    home_banner_copy: 'Browse the full attraction catalog, compare destination types, and open detailed pages for maps and bookings.',
    home_category_spotlight: 'Category Spotlight',
    home_category_copy: 'See what kinds of Kenyan experiences are standing out most in the app right now.',
    home_places_suffix: 'places',
    home_featured_copy: 'Hand-picked destinations to start with before you dive deeper into the full catalog.',
    home_view_destination: 'View destination',
    home_trip_flow_title: 'Trip Flow',
    home_trip_flow_copy: 'A simple path from discovery to movement so the landing page helps you act, not just browse.',
    home_trip_step_one: 'Open a destination that matches your mood, season, or travel style.',
    home_trip_step_two: 'Use the chatbot, wildlife hub, and attraction details to plan with confidence.',
    home_trip_step_three: 'Launch navigation or booking when you are ready to move.',
    featured_attractions: 'Featured Attractions',
    featured_copy: 'Browse a few highlighted destinations, then open the full explore screen for search and filters.',
    explore_all: 'Explore all attractions',
    wildlife_library: 'Wildlife Library',
    wildlife_copy: 'Learn about iconic species, habitats, and conservation efforts.',
    open_wildlife: 'Open Wildlife',
    live_experiences: 'Live Experiences',
    live_copy: 'Open curated wildlife streams and scenic video experiences.',
    open_live: 'Open Live',
    assistant_title: 'Travel Assistant',
    assistant_copy: 'Ask for park tips, safety guidance, and planning advice.',
    open_chatbot: 'Open Chatbot',
    no_attractions: 'No attractions available yet.',
    loading: 'Loading...',
    login_title: 'Welcome Back',
    login_copy: 'Sign in to continue planning your next Kenyan adventure.',
    email: 'Email',
    password: 'Password',
    login: 'Login',
    forgot_password: 'Forgot password?',
    no_account: "Don't have an account? Register",
    register_title: 'Create Your Account',
    register_copy: 'Join Explore Kenya to manage trips, bookings, and destination plans.',
    full_name: 'Full Name',
    phone_number: 'Phone Number',
    register: 'Register',
    already_have_account: 'Already have an account? Login',
    forgot_title: 'Reset Your Password',
    forgot_copy: 'Enter your email to generate a secure reset code.',
    request_code: 'Request Reset Code',
    reset_title: 'Enter Reset Code',
    reset_copy: 'Use the reset code and choose a new password.',
    reset_code: 'Reset Code',
    new_password: 'New Password',
    confirm_password: 'Confirm Password',
    reset_password: 'Reset Password',
    profile_title: 'Profile Management',
    profile_copy: 'Update your account details, interests, and preferred app language.',
    save_profile: 'Save Profile',
    language: 'Language',
    interests: 'Travel Interests',
    logout: 'Logout',
    role: 'Role',
    explore_title: 'Tourist Attractions',
    explore_copy: 'Search by name, filter by category, and open a destination to view details, maps, and bookings.',
    search_placeholder: 'Search attractions or cultural sites',
    all_categories: 'All',
    wildlife_title: 'Wildlife & Conservation',
    wildlife_copy_2: 'Explore species profiles, habitats, and conservation notes.',
    chatbot_title: 'Tourist Assistance Chatbot',
    chatbot_copy:
      'Ask about safari planning, safety guidance, park visits, or payment support. The chatbot uses a MongoDB-backed knowledge base.',
    type_message: 'Ask a question',
    send: 'Send',
    faq: 'Suggested Questions',
    chatbot_no_response: 'No response available.',
    chatbot_unavailable: 'The assistant could not answer right now.',
    profile_saved: 'Your profile was updated successfully.',
    reset_code_generated: 'Reset code generated.',
    use_code_now: 'Use this code now',
    reset_success: 'Password reset successful.',
    settings: 'Settings',
    guest: 'Guest',
    language_saved: 'Language updated.',
    language_english: 'English',
    language_swahili: 'Kiswahili',
    language_french: 'Francais',
    language_spanish: 'Espanol',
    language_german: 'Deutsch',
    language_chinese: '中文',
    language_arabic: 'العربية',
    landing_badge: 'Wildlife & Tourist Attractions',
    landing_title: 'Discover the Magic of Kenya',
    landing_copy:
      "Experience breathtaking wildlife, rich culture, and unforgettable adventures across Kenya's most iconic destinations. Now with 20+ parks and reserves.",
    landing_explore: 'Explore destinations',
    landing_watch_live: 'Watch live',
    landing_stat_parks: 'Parks & Reserves',
    landing_stat_visitors: 'Visitors Monthly',
    landing_stat_rating: 'App Rating',
    landing_ready_label: 'READY TO EXPLORE',
    landing_ready_title: 'Discover Kenya Attractions',
    landing_ready_copy: '20+ parks, reserves, beaches across Kenya with full filtering & maps.',
    landing_explore_title: 'Explore all attractions',
    landing_explore_copy: '20+ parks, reserves & beaches across Kenya',
    landing_feature_navigation_title: 'GPS navigation',
    landing_feature_navigation_copy: 'Real-time maps to every attraction across Kenya.',
    landing_feature_mpesa_title: 'M-Pesa booking',
    landing_feature_mpesa_copy: 'Pay instantly with M-Pesa STK push.',
    landing_feature_live_title: 'Live streaming',
    landing_feature_live_copy: 'Watch wildlife live from any park.',
    landing_feature_language_title: 'Language support',
    landing_feature_language_copy: 'Full support for major tourist languages across the app.',
    landing_booking_title: 'Quick booking',
    landing_booking_cta: 'Get started',
    landing_footer_about: 'About',
    landing_footer_live: 'Live cams',
    landing_footer_bookings: 'Bookings',
    back: 'Back',
    continue_button: 'Continue',
    error: 'Error',
    login_cta: 'Login',
    auth_enter_email: 'Enter your email',
    auth_enter_password: 'Enter your password',
    auth_enter_full_name: 'Enter your full name',
    auth_phone_mpesa: 'Phone (M-Pesa)',
    auth_phone_placeholder: '07XX XXX XXX',
    auth_register_missing: 'Please complete your name, email, and password.',
    auth_password_short: 'Password must be at least 6 characters long.',
    reset_required_fields: 'Please complete all required fields.',
    reset_password_mismatch: 'Password confirmation does not match.',
    wildlife_search_placeholder: 'Search wildlife or region',
    wildlife_empty: 'No wildlife records found.',
    wildlife_habitat: 'Habitat',
    wildlife_conservation: 'Conservation',
    bookings_title: 'My Bookings',
    bookings_new: '+ New',
    bookings_none_title: 'No bookings yet',
    bookings_none_desc: 'Explore attractions and make your first booking.',
    bookings_explore_cta: 'Explore attractions',
    bookings_package: 'Package',
    bookings_visitors: 'Visitors',
    bookings_total: 'Total',
    bookings_receipt: 'M-Pesa receipt',
    bookings_attraction: 'Attraction',
    status_paid: 'Paid',
    status_pending: 'Pending',
    status_failed: 'Failed',
    live_title: 'Live Cameras',
    live_waiting: 'Waiting for park camera...',
    live_leave: 'Leave',
    live_watch: 'Watch',
    live_offline: 'Offline',
    live_all_cameras: 'All park cameras',
    live_refresh: 'Refresh',
    live_empty_title: 'No streams available',
    live_empty_desc: 'Park cameras will appear here when live.',
    live_failed_load: 'Failed to load streams',
    live_failed_join: 'Failed to join stream',
    attraction_loading: 'Loading attraction details...',
    attraction_unavailable: 'Attraction unavailable',
    attraction_not_found: 'This attraction could not be found.',
    attraction_back_to_list: 'Back to attractions',
    attraction_discover_copy: 'Discover this Kenyan destination.',
    attraction_resident_fee: 'Resident fee',
    attraction_nonresident_fee: 'Non-resident fee',
    attraction_quick_actions: 'Quick actions',
    attraction_book_now: 'Book Now',
    attraction_book_copy: 'Open the booking checkout for this attraction.',
    attraction_go_live: 'Go Live',
    attraction_go_live_copy: 'Start or manage a live stream for this attraction.',
    attraction_gps_navigation: 'GPS Navigation',
    attraction_gps_missing: 'GPS coordinates are not available for this attraction yet.',
    attraction_gps_copy: 'Open turn-by-turn map guidance to this attraction.',
    attraction_location: 'Location',
    attraction_coords_missing: 'Coordinates have not been added for this attraction yet.',
    checkout_title: 'Booking Checkout',
    checkout_subtitle: 'Choose how you want to pay, then confirm your reservation details below.',
    checkout_phone_required: 'Phone required',
    checkout_phone_required_copy: 'Enter the phone number to use for this booking.',
    checkout_missing_details: 'Missing details',
    checkout_missing_card: 'Please complete all card details.',
    checkout_invalid_card: 'Invalid card',
    checkout_invalid_card_copy: 'Please enter a valid card number.',
    checkout_mpesa_sent: 'M-Pesa Prompt Sent',
    checkout_payment_success: 'Payment Successful',
    checkout_payment_failed: 'Payment failed',
    checkout_check_phone: 'Check your phone for the M-Pesa STK push prompt.',
    checkout_card_success: 'Your card payment and booking were completed.',
    checkout_back: 'Back',
    checkout_complete_booking: 'Complete your booking for',
    checkout_summary_package: 'Package',
    checkout_summary_date: 'Travel date',
    checkout_summary_participants: 'Participants',
    checkout_payment_method: 'Payment Method',
    checkout_method_mpesa: 'M-Pesa',
    checkout_method_mpesa_copy: 'Production-ready STK push flow',
    checkout_method_card: 'Card',
    checkout_method_card_copy: 'Instant reservation confirmation',
    checkout_phone_placeholder: 'M-Pesa / booking phone number',
    checkout_mpesa_title: 'M-Pesa STK Push',
    checkout_mpesa_notice: 'Use a valid Safaricom number in 07XXXXXXXX, 2547XXXXXXXX, or +2547XXXXXXXX format to receive the payment prompt.',
    checkout_card_details: 'Card Details',
    checkout_cardholder_name: 'Cardholder name',
    checkout_card_number: 'Card number',
    checkout_expiry: 'MM/YY',
    checkout_cvv: 'CVV',
    checkout_sending_mpesa: 'Sending M-Pesa Prompt...',
    checkout_processing_payment: 'Processing Payment...',
    checkout_pay_mpesa: 'Pay with M-Pesa',
    checkout_pay_card: 'Pay by Card',
    map_location_settings: 'Turn on device location services to use in-app turn-by-turn guidance.',
    map_permission_required: 'Location permission is required for in-app turn-by-turn guidance.',
    map_unavailable: 'Map unavailable',
    map_load_failed: 'Could not load map data.',
    map_directions_unavailable: 'Directions unavailable',
    map_no_coords: 'No coordinates found for this attraction.',
    map_open_failed: 'Could not open navigation on this device.',
    map_no_route: 'No route could be generated for this destination.',
    map_loading_title: 'Loading map',
    map_loading_copy: 'Preparing destination and GPS details.',
    map_header_subtitle: 'In-app GPS guidance with a live route, distance, and next maneuver.',
    map_nav_title: 'Turn-by-turn navigation',
    map_remaining: 'Remaining',
    map_eta: 'ETA',
    map_next_instruction: 'Next instruction',
    map_arrived: 'You have arrived near your destination.',
    map_route_appears: 'Route guidance will appear once the route loads.',
    map_destination_label: 'Destination',
    map_coords_missing: 'Coordinates are not available for this attraction yet.',
    map_refresh_route: 'Refresh In-App Route',
    map_open_google: 'Open in Google Maps',
    map_using_last_known: 'Showing your last known position until GPS becomes available.',
    map_instruction_start: 'Start on your route.',
    map_instruction_follow_road: 'Follow the route via',
    map_instruction_follow_route: 'Continue on the route.',
    map_instruction_arrive: 'You are about to arrive at your destination.',
    map_step_in: 'In',
    broadcast_start_failed: 'Failed to start stream',
    broadcast_camera_broadcasting: 'Camera broadcasting',
    broadcast_camera_ready: 'Camera ready',
    broadcast_tap_start: 'Tap Start to go live',
    broadcast_live: 'LIVE',
    broadcast_park_camera: 'Park Camera',
    broadcast_broadcasting_status: 'Broadcasting',
    broadcast_ready_status: 'Ready to stream',
    broadcast_go_live: 'Go Live',
    broadcast_stop_stream: 'Stop stream',
    broadcast_stop_title: 'Stop streaming?',
    broadcast_stop_copy: 'This will end the live stream for all viewers.',
    broadcast_gps_navigation: 'GPS Navigation',
    broadcast_viewers_watching: 'watching',
    broadcast_you_are_live: 'You are live',
    navigation_permission_denied: 'Permission denied',
    navigation_permission_required: 'Location access is required for navigation.',
    navigation_error: 'Failed to start navigation. Please try again.',
    navigation_loading: 'Loading navigation...',
    navigation_live: 'Live navigation',
    navigation_distance: 'Distance',
    navigation_navigate_to: 'Navigate to',
    navigation_you_are_here: 'You are here',
    navigation_your_destination: 'Your destination',
    navigation_map_error: 'Map error',
    catalog_greeting: 'Good morning',
    catalog_search_placeholder: 'Search attractions...',
    catalog_view_more: 'View',
    catalog_empty: 'No attractions found.',
    catalog_bookings: 'Bookings',
    category_all: 'All',
    category_wildlife: 'Wildlife',
    category_culture: 'Culture',
    category_cultural: 'Cultural',
    category_adventure: 'Adventure',
    category_beach: 'Beach',
    category_history: 'History',
    category_historical: 'Historical',
  },
  sw: {
    home: 'Nyumbani',
    explore: 'Vivutio',
    bookings: 'Uhifadhi',
    chatbot: 'Msaidizi',
    profile: 'Wasifu',
    live: 'Moja kwa Moja',
    app_name: 'Explore Kenya',
    welcome_title: 'Gundua mbuga, wanyamapori, tamaduni na msaada wa safari katika programu moja.',
    welcome_copy:
      'Tafuta vivutio, angalia taarifa za wanyamapori, elekezwa kwenye maeneo, dhibiti uhifadhi, na upate msaada wa safari kutoka kwa chatbot.',
    traveler: 'Msafiri',
    home_hero_title: 'Kituo chako cha safari za Kenya kwa mapumziko, kuona wanyama, njia, na maeneo ya kuhifadhi.',
    home_hero_copy:
      'Anza na maeneo yaliyochaguliwa, ingia kwenye maudhui ya wanyamapori, muulize msaidizi kuhusu mipango, na utoke kwenye hamasa hadi urambazaji kwa mibofyo michache.',
    home_ready_label: 'Tayari kwa',
    home_primary_cta: 'Fungua Vivutio',
    home_destinations_label: 'Maeneo yanayopatikana',
    home_categories_label: 'Mada zinazoongoza',
    home_route_ready_label: 'Maeneo yenye njia',
    home_banner_title: 'Panga safari ya leo kwa haraka.',
    home_banner_copy: 'Tazama orodha yote ya vivutio, linganisha aina za maeneo, na fungua kurasa za kina kwa ramani na uhifadhi.',
    home_category_spotlight: 'Mwangaza wa Makundi',
    home_category_copy: 'Angalia aina za uzoefu wa Kenya zinazojitokeza zaidi ndani ya programu kwa sasa.',
    home_places_suffix: 'maeneo',
    home_featured_copy: 'Maeneo machache yaliyopendekezwa ili uanze kabla ya kuingia kwenye orodha nzima.',
    home_view_destination: 'Fungua eneo',
    home_trip_flow_title: 'Mtiririko wa Safari',
    home_trip_flow_copy: 'Njia rahisi kutoka ugunduzi hadi hatua ili ukurasa wa mwanzo usaide kuchukua hatua, si kutazama tu.',
    home_trip_step_one: 'Fungua eneo linalolingana na hamu yako, msimu, au aina ya safari.',
    home_trip_step_two: 'Tumia chatbot, maktaba ya wanyamapori, na maelezo ya vivutio kupanga kwa uhakika.',
    home_trip_step_three: 'Anzisha urambazaji au uhifadhi ukiwa tayari kusonga.',
    featured_attractions: 'Vivutio Vilivyochaguliwa',
    featured_copy: 'Angalia maeneo machache muhimu kisha fungua ukurasa wa vivutio kwa utafutaji na uchujaji.',
    explore_all: 'Fungua vivutio vyote',
    wildlife_library: 'Maktaba ya Wanyamapori',
    wildlife_copy: 'Jifunze kuhusu spishi maarufu, makazi yao, na juhudi za uhifadhi.',
    open_wildlife: 'Fungua Wanyamapori',
    live_experiences: 'Matukio ya Moja kwa Moja',
    live_copy: 'Fungua video za moja kwa moja za wanyamapori na mandhari.',
    open_live: 'Fungua Live',
    assistant_title: 'Msaidizi wa Safari',
    assistant_copy: 'Uliza kuhusu hifadhi, usalama, na ushauri wa kupanga safari.',
    open_chatbot: 'Fungua Chatbot',
    no_attractions: 'Hakuna vivutio kwa sasa.',
    loading: 'Inapakia...',
    login_title: 'Karibu Tena',
    login_copy: 'Ingia ili uendelee kupanga safari yako ijayo nchini Kenya.',
    email: 'Barua pepe',
    password: 'Nenosiri',
    login: 'Ingia',
    forgot_password: 'Umesahau nenosiri?',
    no_account: 'Huna akaunti? Jisajili',
    register_title: 'Tengeneza Akaunti',
    register_copy: 'Jiunge na Explore Kenya kusimamia safari, uhifadhi, na mipango ya maeneo.',
    full_name: 'Jina Kamili',
    phone_number: 'Namba ya Simu',
    register: 'Jisajili',
    already_have_account: 'Una akaunti tayari? Ingia',
    forgot_title: 'Weka Upya Nenosiri',
    forgot_copy: 'Weka barua pepe yako ili kupata msimbo wa kuweka upya.',
    request_code: 'Omba Msimbo',
    reset_title: 'Weka Msimbo wa Uthibitisho',
    reset_copy: 'Tumia msimbo wa kuweka upya na chagua nenosiri jipya.',
    reset_code: 'Msimbo wa Uthibitisho',
    new_password: 'Nenosiri Jipya',
    confirm_password: 'Thibitisha Nenosiri',
    reset_password: 'Weka Upya Nenosiri',
    profile_title: 'Usimamizi wa Wasifu',
    profile_copy: 'Sasisha taarifa za akaunti, mapendeleo, na lugha ya programu.',
    save_profile: 'Hifadhi Wasifu',
    language: 'Lugha',
    interests: 'Mambo Unayopenda',
    logout: 'Toka',
    role: 'Jukumu',
    explore_title: 'Vivutio vya Watalii',
    explore_copy: 'Tafuta kwa jina, chuja kwa kundi, na fungua eneo kuona maelezo, ramani, na uhifadhi.',
    search_placeholder: 'Tafuta vivutio au maeneo ya kitamaduni',
    all_categories: 'Yote',
    wildlife_title: 'Wanyamapori na Uhifadhi',
    wildlife_copy_2: 'Chunguza profaili za spishi, makazi, na taarifa za uhifadhi.',
    chatbot_title: 'Chatbot ya Msaada wa Watalii',
    chatbot_copy:
      'Uliza kuhusu kupanga safari, usalama, kutembelea mbuga, au malipo. Chatbot hutumia maarifa yaliyohifadhiwa MongoDB.',
    type_message: 'Uliza swali',
    send: 'Tuma',
    faq: 'Maswali Yanayopendekezwa',
    chatbot_no_response: 'Hakuna jibu lililopatikana.',
    chatbot_unavailable: 'Msaidizi hakuweza kujibu kwa sasa.',
    profile_saved: 'Wasifu wako umehifadhiwa kwa mafanikio.',
    reset_code_generated: 'Msimbo wa kuweka upya umetengenezwa.',
    use_code_now: 'Tumia msimbo huu sasa',
    reset_success: 'Nenosiri limewekwa upya kwa mafanikio.',
    settings: 'Mipangilio',
    guest: 'Mgeni',
    language_saved: 'Lugha imesasishwa.',
    language_english: 'Kiingereza',
    language_swahili: 'Kiswahili',
    language_french: 'Kifaransa',
    language_spanish: 'Kihispania',
    language_german: 'Kijerumani',
    language_chinese: 'Kichina',
    language_arabic: 'Kiarabu',
    landing_badge: 'Wanyamapori na Vivutio vya Watalii',
    landing_title: 'Gundua Uzuri wa Kenya',
    landing_copy:
      'Furahia wanyamapori wa kuvutia, tamaduni tajiri, na matukio yasiyosahaulika katika maeneo maarufu zaidi ya Kenya. Sasa na zaidi ya mbuga na hifadhi 20.',
    landing_explore: 'Chunguza maeneo',
    landing_watch_live: 'Tazama moja kwa moja',
    landing_stat_parks: 'Mbuga na Hifadhi',
    landing_stat_visitors: 'Watembeleaji kwa mwezi',
    landing_stat_rating: 'Ukadiriaji wa programu',
    landing_ready_label: 'TAYARI KUCHUNGUZA',
    landing_ready_title: 'Gundua Vivutio vya Kenya',
    landing_ready_copy: 'Zaidi ya mbuga, hifadhi, na fukwe 20 nchini Kenya zikiwa na uchujaji kamili na ramani.',
    landing_explore_title: 'Chunguza vivutio vyote',
    landing_explore_copy: 'Zaidi ya mbuga, hifadhi na fukwe 20 nchini Kenya',
    landing_feature_navigation_title: 'Urambazaji wa GPS',
    landing_feature_navigation_copy: 'Ramani za muda halisi kwa kila kivutio nchini Kenya.',
    landing_feature_mpesa_title: 'Uhifadhi wa M-Pesa',
    landing_feature_mpesa_copy: 'Lipa papo hapo kupitia M-Pesa STK push.',
    landing_feature_live_title: 'Matangazo ya moja kwa moja',
    landing_feature_live_copy: 'Tazama wanyamapori moja kwa moja kutoka hifadhi yoyote.',
    landing_feature_language_title: 'Msaada wa lugha',
    landing_feature_language_copy: 'Msaada kamili wa lugha muhimu zinazotumiwa na watalii ndani ya programu.',
    landing_booking_title: 'Uhifadhi wa haraka',
    landing_booking_cta: 'Anza sasa',
    landing_footer_about: 'Kuhusu',
    landing_footer_live: 'Kamera za moja kwa moja',
    landing_footer_bookings: 'Uhifadhi',
    back: 'Rudi',
    continue_button: 'Endelea',
    error: 'Hitilafu',
    login_cta: 'Ingia',
    auth_enter_email: 'Weka barua pepe yako',
    auth_enter_password: 'Weka nenosiri lako',
    auth_enter_full_name: 'Weka jina lako kamili',
    auth_phone_mpesa: 'Simu ya M-Pesa',
    auth_phone_placeholder: '07XX XXX XXX',
    auth_register_missing: 'Tafadhali jaza jina, barua pepe na nenosiri.',
    auth_password_short: 'Nenosiri lazima liwe na angalau herufi 6.',
    reset_required_fields: 'Tafadhali jaza sehemu zote zinazohitajika.',
    reset_password_mismatch: 'Uthibitisho wa nenosiri haulingani.',
    wildlife_search_placeholder: 'Tafuta wanyamapori au eneo',
    wildlife_empty: 'Hakuna rekodi za wanyamapori zilizopatikana.',
    wildlife_habitat: 'Makazi',
    wildlife_conservation: 'Uhifadhi',
    bookings_title: 'Uhifadhi Wangu',
    bookings_new: '+ Mpya',
    bookings_none_title: 'Bado hakuna uhifadhi',
    bookings_none_desc: 'Chunguza vivutio na ufanye uhifadhi wako wa kwanza.',
    bookings_explore_cta: 'Chunguza vivutio',
    bookings_package: 'Kifurushi',
    bookings_visitors: 'Wageni',
    bookings_total: 'Jumla',
    bookings_receipt: 'Risiti ya M-Pesa',
    bookings_attraction: 'Kivutio',
    status_paid: 'Imelipwa',
    status_pending: 'Inasubiri',
    status_failed: 'Imeshindikana',
    live_title: 'Kamera za Moja kwa Moja',
    live_waiting: 'Inasubiri kamera ya hifadhi...',
    live_leave: 'Ondoka',
    live_watch: 'Tazama',
    live_offline: 'Haipo hewani',
    live_all_cameras: 'Kamera zote za hifadhi',
    live_refresh: 'Pakia upya',
    live_empty_title: 'Hakuna matangazo yaliyopo',
    live_empty_desc: 'Kamera za hifadhi zitaonekana hapa zikiwa hewani.',
    live_failed_load: 'Imeshindwa kupakia matangazo',
    live_failed_join: 'Imeshindwa kujiunga na matangazo',
    attraction_loading: 'Inapakia maelezo ya kivutio...',
    attraction_unavailable: 'Kivutio hakipatikani',
    attraction_not_found: 'Kivutio hiki hakikupatikana.',
    attraction_back_to_list: 'Rudi kwenye vivutio',
    attraction_discover_copy: 'Gundua kivutio hiki cha Kenya.',
    attraction_resident_fee: 'Ada ya mkazi',
    attraction_nonresident_fee: 'Ada ya asiye mkazi',
    attraction_quick_actions: 'Hatua za haraka',
    attraction_book_now: 'Hifadhi Sasa',
    attraction_book_copy: 'Fungua malipo ya uhifadhi kwa kivutio hiki.',
    attraction_go_live: 'Nenda Live',
    attraction_go_live_copy: 'Anza au dhibiti matangazo ya moja kwa moja kwa kivutio hiki.',
    attraction_gps_navigation: 'Urambazaji wa GPS',
    attraction_gps_missing: 'Kuratibu za GPS hazijapatikana kwa kivutio hiki bado.',
    attraction_gps_copy: 'Fungua mwongozo wa ramani ya hatua kwa hatua kwa kivutio hiki.',
    attraction_location: 'Mahali',
    attraction_coords_missing: 'Kuratibu hazijaongezwa kwa kivutio hiki bado.',
    checkout_title: 'Malipo ya Uhifadhi',
    checkout_subtitle: 'Chagua jinsi ya kulipa kisha thibitisha maelezo ya uhifadhi hapa chini.',
    checkout_phone_required: 'Namba ya simu inahitajika',
    checkout_phone_required_copy: 'Weka namba ya simu itakayotumika kwa uhifadhi huu.',
    checkout_missing_details: 'Maelezo hayajakamilika',
    checkout_missing_card: 'Tafadhali jaza maelezo yote ya kadi.',
    checkout_invalid_card: 'Kadi si sahihi',
    checkout_invalid_card_copy: 'Tafadhali weka namba sahihi ya kadi.',
    checkout_mpesa_sent: 'Ombi la M-Pesa limetumwa',
    checkout_payment_success: 'Malipo yamefanikiwa',
    checkout_payment_failed: 'Malipo yameshindikana',
    checkout_check_phone: 'Angalia simu yako kwa ombi la M-Pesa STK push.',
    checkout_card_success: 'Malipo ya kadi na uhifadhi yamekamilika.',
    checkout_back: 'Rudi',
    checkout_complete_booking: 'Kamilisha uhifadhi wako wa',
    checkout_summary_package: 'Kifurushi',
    checkout_summary_date: 'Tarehe ya safari',
    checkout_summary_participants: 'Washiriki',
    checkout_payment_method: 'Njia ya Malipo',
    checkout_method_mpesa: 'M-Pesa',
    checkout_method_mpesa_copy: 'Mtiririko wa STK push wa uzalishaji',
    checkout_method_card: 'Kadi',
    checkout_method_card_copy: 'Uthibitisho wa uhifadhi wa papo hapo',
    checkout_phone_placeholder: 'Namba ya simu ya M-Pesa / uhifadhi',
    checkout_mpesa_title: 'M-Pesa STK Push',
    checkout_mpesa_notice: 'Tumia namba halali ya Safaricom katika muundo wa 07XXXXXXXX, 2547XXXXXXXX, au +2547XXXXXXXX kupokea ombi la malipo.',
    checkout_card_details: 'Maelezo ya Kadi',
    checkout_cardholder_name: 'Jina la mwenye kadi',
    checkout_card_number: 'Namba ya kadi',
    checkout_expiry: 'MM/YY',
    checkout_cvv: 'CVV',
    checkout_sending_mpesa: 'Inatuma Ombi la M-Pesa...',
    checkout_processing_payment: 'Inachakata malipo...',
    checkout_pay_mpesa: 'Lipa kwa M-Pesa',
    checkout_pay_card: 'Lipa kwa Kadi',
    map_location_settings: 'Washa huduma za eneo la kifaa ili kutumia mwongozo wa GPS wa ndani ya programu.',
    map_permission_required: 'Ruhusa ya eneo inahitajika kwa mwongozo wa ndani ya programu.',
    map_unavailable: 'Ramani haipatikani',
    map_load_failed: 'Haikuweza kupakia data ya ramani.',
    map_directions_unavailable: 'Maelekezo hayapatikani',
    map_no_coords: 'Hakuna kuratibu zilizopatikana kwa kivutio hiki.',
    map_open_failed: 'Haikuweza kufungua urambazaji kwenye kifaa hiki.',
    map_no_route: 'Njia haikuweza kutengenezwa kwa kivutio hiki.',
    map_loading_title: 'Inapakia ramani',
    map_loading_copy: 'Inaandaa mahali unakoenda na taarifa za GPS.',
    map_header_subtitle: 'Mwongozo wa GPS ndani ya programu wenye njia ya moja kwa moja, umbali na hatua inayofuata.',
    map_nav_title: 'Urambazaji wa hatua kwa hatua',
    map_remaining: 'Iliyobaki',
    map_eta: 'Muda wa kufika',
    map_next_instruction: 'Maelekezo yanayofuata',
    map_arrived: 'Umefika karibu na unakoenda.',
    map_route_appears: 'Mwongozo wa njia utaonekana mara tu njia inapopakiwa.',
    map_destination_label: 'Unakoenda',
    map_coords_missing: 'Kuratibu hazipatikani kwa kivutio hiki bado.',
    map_refresh_route: 'Pakia Upya Njia ya Ndani ya Programu',
    map_open_google: 'Fungua kwenye Google Maps',
    map_using_last_known: 'Inaonyesha eneo lako la mwisho linalojulikana hadi GPS ipatikane.',
    map_instruction_start: 'Anza kufuata njia yako.',
    map_instruction_follow_road: 'Fuata njia kupitia',
    map_instruction_follow_route: 'Endelea kwenye njia.',
    map_instruction_arrive: 'Unakaribia kufika unakoenda.',
    map_step_in: 'Baada ya',
    broadcast_start_failed: 'Imeshindwa kuanzisha matangazo',
    broadcast_camera_broadcasting: 'Kamera inarusha matangazo',
    broadcast_camera_ready: 'Kamera iko tayari',
    broadcast_tap_start: 'Gusa Anza kwenda live',
    broadcast_live: 'LIVE',
    broadcast_park_camera: 'Kamera ya Hifadhi',
    broadcast_broadcasting_status: 'Inarusha matangazo',
    broadcast_ready_status: 'Iko tayari kurusha',
    broadcast_go_live: 'Nenda Live',
    broadcast_stop_stream: 'Simamisha matangazo',
    broadcast_stop_title: 'Simamisha matangazo?',
    broadcast_stop_copy: 'Hii itasitisha matangazo ya moja kwa moja kwa watazamaji wote.',
    broadcast_gps_navigation: 'Urambazaji wa GPS',
    broadcast_viewers_watching: 'wanatazama',
    broadcast_you_are_live: 'Uko live',
    navigation_permission_denied: 'Ruhusa imekataliwa',
    navigation_permission_required: 'Ufikiaji wa eneo unahitajika kwa urambazaji.',
    navigation_error: 'Imeshindwa kuanzisha urambazaji. Tafadhali jaribu tena.',
    navigation_loading: 'Inapakia urambazaji...',
    navigation_live: 'Urambazaji wa moja kwa moja',
    navigation_distance: 'Umbali',
    navigation_navigate_to: 'Elekea',
    navigation_you_are_here: 'Uko hapa',
    navigation_your_destination: 'Unakoenda',
    navigation_map_error: 'Hitilafu ya ramani',
    catalog_greeting: 'Habari za asubuhi',
    catalog_search_placeholder: 'Tafuta vivutio...',
    catalog_view_more: 'Tazama',
    catalog_empty: 'Hakuna vivutio vilivyopatikana.',
    catalog_bookings: 'Uhifadhi',
    category_all: 'Zote',
    category_wildlife: 'Wanyamapori',
    category_culture: 'Utamaduni',
    category_cultural: 'Kitamaduni',
    category_adventure: 'Matukio',
    category_beach: 'Fukwe',
    category_history: 'Historia',
    category_historical: 'Kihistoria',
  },
  fr: {
    home: 'Accueil',
    explore: 'Attractions',
    bookings: 'Reservations',
    chatbot: 'Assistant',
    profile: 'Profil',
    live: 'En direct',
    login_title: 'Bon retour',
    login_copy: 'Connectez-vous pour continuer a planifier votre prochaine aventure au Kenya.',
    register_title: 'Creez votre compte',
    register_copy: 'Rejoignez Explore Kenya pour gerer vos voyages, reservations et projets.',
    forgot_title: 'Reinitialiser votre mot de passe',
    forgot_copy: 'Entrez votre e-mail pour generer un code securise.',
    reset_title: 'Entrer le code de reinitialisation',
    reset_copy: 'Utilisez le code et choisissez un nouveau mot de passe.',
    full_name: 'Nom complet',
    phone_number: 'Numero de telephone',
    register: 'Inscription',
    login: 'Connexion',
    forgot_password: 'Mot de passe oublie ?',
    no_account: 'Pas de compte ? Inscrivez-vous',
    already_have_account: 'Vous avez deja un compte ? Connectez-vous',
    language: 'Langue',
    interests: 'Interets de voyage',
    save_profile: 'Enregistrer le profil',
    logout: 'Deconnexion',
    profile_title: 'Gestion du profil',
    profile_copy: 'Mettez a jour votre compte, vos interets et votre langue preferee.',
    settings: 'Parametres',
    language_saved: 'Langue mise a jour.',
    profile_saved: 'Votre profil a ete mis a jour avec succes.',
    loading: 'Chargement...',
    language_english: 'English',
    language_swahili: 'Kiswahili',
    language_french: 'Francais',
    language_spanish: 'Espagnol',
    language_german: 'Allemand',
    language_chinese: 'Chinois',
    language_arabic: 'Arabe',
    landing_badge: 'Faune et attractions touristiques',
    landing_title: 'Decouvrez la magie du Kenya',
    landing_copy: 'Profitez d une faune spectaculaire, d une culture riche et d aventures memorables a travers le Kenya.',
    landing_explore: 'Explorer les destinations',
    landing_watch_live: 'Regarder en direct',
    landing_stat_parks: 'Parcs et reserves',
    landing_stat_visitors: 'Visiteurs mensuels',
    landing_stat_rating: 'Note de l application',
    landing_ready_label: 'PRET A EXPLORER',
    landing_ready_title: 'Decouvrez les attractions du Kenya',
    landing_ready_copy: 'Plus de 20 parcs, reserves et plages avec cartes et filtres complets.',
    landing_explore_title: 'Explorer toutes les attractions',
    landing_explore_copy: 'Plus de 20 parcs, reserves et plages au Kenya',
    landing_feature_navigation_title: 'Navigation GPS',
    landing_feature_navigation_copy: 'Cartes en temps reel vers chaque attraction.',
    landing_feature_mpesa_title: 'Reservation M-Pesa',
    landing_feature_mpesa_copy: 'Payez instantanement avec M-Pesa STK push.',
    landing_feature_live_title: 'Diffusion en direct',
    landing_feature_live_copy: 'Regardez la faune en direct depuis n importe quel parc.',
    landing_feature_language_title: 'Prise en charge des langues',
    landing_feature_language_copy: 'Prise en charge complete des principales langues touristiques.',
    landing_booking_title: 'Reservation rapide',
    landing_booking_cta: 'Commencer',
    landing_footer_about: 'A propos',
    landing_footer_live: 'Cameras en direct',
    landing_footer_bookings: 'Reservations',
    broadcast_viewers_watching: 'spectateurs',
    broadcast_you_are_live: 'Vous etes en direct',
    navigation_you_are_here: 'Vous etes ici',
    navigation_your_destination: 'Votre destination',
    navigation_map_error: 'Erreur de carte',
    catalog_greeting: 'Bonjour',
    catalog_search_placeholder: 'Rechercher des attractions...',
    catalog_view_more: 'Voir',
    catalog_empty: 'Aucune attraction trouvee.',
    catalog_bookings: 'Reservations',
    category_all: 'Tout',
    category_wildlife: 'Faune',
    category_culture: 'Culture',
    category_cultural: 'Culturel',
    category_adventure: 'Aventure',
    category_beach: 'Plage',
    category_history: 'Histoire',
    category_historical: 'Historique',
    auth_phone_placeholder: '07XX XXX XXX',
    chatbot_no_response: 'Aucune reponse disponible.',
    chatbot_unavailable: 'L assistant ne peut pas repondre pour le moment.',
    map_using_last_known: 'Affichage de votre derniere position connue jusqu a ce que le GPS soit disponible.',
    map_instruction_start: 'Commencez votre itineraire.',
    map_instruction_follow_road: 'Suivez l itineraire via',
    map_instruction_follow_route: 'Continuez sur l itineraire.',
    map_instruction_arrive: 'Vous etes presque arrive a votre destination.',
    map_step_in: 'Dans',
  },
  es: {
    home: 'Inicio',
    explore: 'Atracciones',
    bookings: 'Reservas',
    chatbot: 'Asistente',
    profile: 'Perfil',
    live: 'En vivo',
    login_title: 'Bienvenido de nuevo',
    login_copy: 'Inicia sesion para seguir planificando tu proxima aventura en Kenia.',
    register_title: 'Crea tu cuenta',
    register_copy: 'Unete a Explore Kenya para gestionar viajes, reservas y planes.',
    forgot_title: 'Restablece tu contrasena',
    forgot_copy: 'Ingresa tu correo para generar un codigo seguro.',
    reset_title: 'Ingresa el codigo de restablecimiento',
    reset_copy: 'Usa el codigo y elige una nueva contrasena.',
    full_name: 'Nombre completo',
    phone_number: 'Numero de telefono',
    register: 'Registrarse',
    login: 'Iniciar sesion',
    forgot_password: 'Olvidaste tu contrasena?',
    no_account: 'No tienes cuenta? Registrate',
    already_have_account: 'Ya tienes cuenta? Inicia sesion',
    language: 'Idioma',
    interests: 'Intereses de viaje',
    save_profile: 'Guardar perfil',
    logout: 'Cerrar sesion',
    profile_title: 'Gestion del perfil',
    profile_copy: 'Actualiza tu cuenta, intereses e idioma preferido.',
    settings: 'Configuracion',
    language_saved: 'Idioma actualizado.',
    profile_saved: 'Tu perfil se actualizo correctamente.',
    loading: 'Cargando...',
    language_english: 'Ingles',
    language_swahili: 'Suajili',
    language_french: 'Frances',
    language_spanish: 'Espanol',
    language_german: 'Aleman',
    language_chinese: 'Chino',
    language_arabic: 'Arabe',
    landing_badge: 'Fauna y atracciones turisticas',
    landing_title: 'Descubre la magia de Kenia',
    landing_copy: 'Disfruta de fauna impresionante, cultura rica y aventuras inolvidables por todo Kenia.',
    landing_explore: 'Explorar destinos',
    landing_watch_live: 'Ver en vivo',
    landing_stat_parks: 'Parques y reservas',
    landing_stat_visitors: 'Visitantes mensuales',
    landing_stat_rating: 'Calificacion de la app',
    landing_ready_label: 'LISTO PARA EXPLORAR',
    landing_ready_title: 'Descubre las atracciones de Kenia',
    landing_ready_copy: 'Mas de 20 parques, reservas y playas con filtros completos y mapas.',
    landing_explore_title: 'Explorar todas las atracciones',
    landing_explore_copy: 'Mas de 20 parques, reservas y playas en Kenia',
    landing_feature_navigation_title: 'Navegacion GPS',
    landing_feature_navigation_copy: 'Mapas en tiempo real para cada atraccion.',
    landing_feature_mpesa_title: 'Reserva con M-Pesa',
    landing_feature_mpesa_copy: 'Paga al instante con M-Pesa STK push.',
    landing_feature_live_title: 'Transmision en vivo',
    landing_feature_live_copy: 'Mira fauna en vivo desde cualquier parque.',
    landing_feature_language_title: 'Soporte de idiomas',
    landing_feature_language_copy: 'Soporte completo para idiomas importantes de turistas.',
    landing_booking_title: 'Reserva rapida',
    landing_booking_cta: 'Comenzar',
    landing_footer_about: 'Acerca de',
    landing_footer_live: 'Camaras en vivo',
    landing_footer_bookings: 'Reservas',
    broadcast_viewers_watching: 'viendo',
    broadcast_you_are_live: 'Estas en vivo',
    navigation_you_are_here: 'Estas aqui',
    navigation_your_destination: 'Tu destino',
    navigation_map_error: 'Error del mapa',
    catalog_greeting: 'Buenos dias',
    catalog_search_placeholder: 'Buscar atracciones...',
    catalog_view_more: 'Ver',
    catalog_empty: 'No se encontraron atracciones.',
    catalog_bookings: 'Reservas',
    category_all: 'Todo',
    category_wildlife: 'Vida silvestre',
    category_culture: 'Cultura',
    category_cultural: 'Cultural',
    category_adventure: 'Aventura',
    category_beach: 'Playa',
    category_history: 'Historia',
    category_historical: 'Historico',
    auth_phone_placeholder: '07XX XXX XXX',
    chatbot_no_response: 'No hay respuesta disponible.',
    chatbot_unavailable: 'El asistente no pudo responder en este momento.',
    map_using_last_known: 'Mostrando tu ultima ubicacion conocida hasta que el GPS este disponible.',
    map_instruction_start: 'Comienza tu ruta.',
    map_instruction_follow_road: 'Sigue la ruta por',
    map_instruction_follow_route: 'Continua por la ruta.',
    map_instruction_arrive: 'Estas a punto de llegar a tu destino.',
    map_step_in: 'En',
  },
  de: {
    home: 'Start',
    explore: 'Attraktionen',
    bookings: 'Buchungen',
    chatbot: 'Assistent',
    profile: 'Profil',
    live: 'Live',
    login_title: 'Willkommen zuruck',
    login_copy: 'Melden Sie sich an, um Ihr nachstes Kenia-Abenteuer weiter zu planen.',
    register_title: 'Konto erstellen',
    register_copy: 'Treten Sie Explore Kenya bei, um Reisen und Buchungen zu verwalten.',
    forgot_title: 'Passwort zurucksetzen',
    forgot_copy: 'Geben Sie Ihre E-Mail fur einen sicheren Code ein.',
    reset_title: 'Zurucksetzungscode eingeben',
    reset_copy: 'Verwenden Sie den Code und wahlen Sie ein neues Passwort.',
    full_name: 'Vollstandiger Name',
    phone_number: 'Telefonnummer',
    register: 'Registrieren',
    login: 'Anmelden',
    forgot_password: 'Passwort vergessen?',
    no_account: 'Noch kein Konto? Registrieren',
    already_have_account: 'Sie haben bereits ein Konto? Anmelden',
    language: 'Sprache',
    interests: 'Reiseinteressen',
    save_profile: 'Profil speichern',
    logout: 'Abmelden',
    profile_title: 'Profilverwaltung',
    profile_copy: 'Aktualisieren Sie Ihr Konto, Ihre Interessen und Ihre bevorzugte Sprache.',
    settings: 'Einstellungen',
    language_saved: 'Sprache aktualisiert.',
    profile_saved: 'Ihr Profil wurde erfolgreich aktualisiert.',
    loading: 'Wird geladen...',
    language_english: 'Englisch',
    language_swahili: 'Swahili',
    language_french: 'Franzosisch',
    language_spanish: 'Spanisch',
    language_german: 'Deutsch',
    language_chinese: 'Chinesisch',
    language_arabic: 'Arabisch',
    landing_badge: 'Tierwelt und Touristenattraktionen',
    landing_title: 'Entdecken Sie die Magie Kenias',
    landing_copy: 'Erleben Sie beeindruckende Tierwelt, reiche Kultur und unvergessliche Abenteuer in Kenia.',
    landing_explore: 'Ziele entdecken',
    landing_watch_live: 'Live ansehen',
    landing_stat_parks: 'Parks und Reservate',
    landing_stat_visitors: 'Monatliche Besucher',
    landing_stat_rating: 'App-Bewertung',
    landing_ready_label: 'BEREIT ZUM ENTDECKEN',
    landing_ready_title: 'Entdecken Sie Kenias Attraktionen',
    landing_ready_copy: 'Mehr als 20 Parks, Reservate und Strande mit Filtern und Karten.',
    landing_explore_title: 'Alle Attraktionen entdecken',
    landing_explore_copy: 'Mehr als 20 Parks, Reservate und Strande in Kenia',
    landing_feature_navigation_title: 'GPS-Navigation',
    landing_feature_navigation_copy: 'Echtzeitkarten zu jeder Attraktion.',
    landing_feature_mpesa_title: 'M-Pesa-Buchung',
    landing_feature_mpesa_copy: 'Sofort mit M-Pesa STK push bezahlen.',
    landing_feature_live_title: 'Live-Streaming',
    landing_feature_live_copy: 'Beobachten Sie Tierwelt live aus jedem Park.',
    landing_feature_language_title: 'Sprachunterstutzung',
    landing_feature_language_copy: 'Volle Unterstutzung fur wichtige Touristensprachen.',
    landing_booking_title: 'Schnellbuchung',
    landing_booking_cta: 'Loslegen',
    landing_footer_about: 'Uber uns',
    landing_footer_live: 'Live-Kameras',
    landing_footer_bookings: 'Buchungen',
    broadcast_viewers_watching: 'sehen zu',
    broadcast_you_are_live: 'Sie sind live',
    navigation_you_are_here: 'Sie sind hier',
    navigation_your_destination: 'Ihr Ziel',
    navigation_map_error: 'Kartenfehler',
    catalog_greeting: 'Guten Morgen',
    catalog_search_placeholder: 'Attraktionen suchen...',
    catalog_view_more: 'Ansehen',
    catalog_empty: 'Keine Attraktionen gefunden.',
    catalog_bookings: 'Buchungen',
    category_all: 'Alle',
    category_wildlife: 'Tierwelt',
    category_culture: 'Kultur',
    category_cultural: 'Kulturell',
    category_adventure: 'Abenteuer',
    category_beach: 'Strand',
    category_history: 'Geschichte',
    category_historical: 'Historisch',
    error: 'Fehler',
    back: 'Zuruck',
    continue_button: 'Weiter',
    login_cta: 'Anmelden',
    email: 'E-Mail',
    password: 'Passwort',
    request_code: 'Code anfordern',
    reset_code: 'Zurucksetzungscode',
    new_password: 'Neues Passwort',
    confirm_password: 'Passwort bestatigen',
    reset_password: 'Passwort zurucksetzen',
    auth_enter_email: 'E-Mail eingeben',
    auth_enter_password: 'Passwort eingeben',
    auth_enter_full_name: 'Vollstandigen Namen eingeben',
    auth_phone_mpesa: 'Telefon (M-Pesa)',
    auth_phone_placeholder: '07XX XXX XXX',
    auth_register_missing: 'Bitte Name, E-Mail und Passwort ausfullen.',
    auth_password_short: 'Das Passwort muss mindestens 6 Zeichen lang sein.',
    reset_required_fields: 'Bitte alle erforderlichen Felder ausfullen.',
    reset_password_mismatch: 'Die Passwortbestatigung stimmt nicht uberein.',
    wildlife_library: 'Tierwelt-Bibliothek',
    wildlife_title: 'Tierwelt und Naturschutz',
    wildlife_copy_2: 'Entdecken Sie Artenprofile, Lebensraume und Naturschutzinfos.',
    wildlife_search_placeholder: 'Tierwelt oder Region suchen',
    wildlife_empty: 'Keine Tierwelt-Eintrage gefunden.',
    wildlife_habitat: 'Lebensraum',
    wildlife_conservation: 'Naturschutz',
    chatbot_title: 'Touristen-Assistent',
    chatbot_copy: 'Fragen Sie nach Safari-Planung, Sicherheit, Parkbesuchen oder Zahlungen.',
    type_message: 'Eine Frage stellen',
    send: 'Senden',
    faq: 'Vorgeschlagene Fragen',
    chatbot_no_response: 'Keine Antwort verfugbar.',
    chatbot_unavailable: 'Der Assistent konnte gerade nicht antworten.',
    bookings_title: 'Meine Buchungen',
    bookings_new: '+ Neu',
    bookings_none_title: 'Noch keine Buchungen',
    bookings_none_desc: 'Entdecken Sie Attraktionen und erstellen Sie Ihre erste Buchung.',
    bookings_explore_cta: 'Attraktionen entdecken',
    bookings_package: 'Paket',
    bookings_visitors: 'Besucher',
    bookings_total: 'Gesamt',
    bookings_receipt: 'M-Pesa-Beleg',
    bookings_attraction: 'Attraktion',
    status_paid: 'Bezahlt',
    status_pending: 'Ausstehend',
    status_failed: 'Fehlgeschlagen',
    live_title: 'Live-Kameras',
    live_waiting: 'Warten auf Parkkamera...',
    live_leave: 'Verlassen',
    live_watch: 'Ansehen',
    live_offline: 'Offline',
    live_all_cameras: 'Alle Parkkameras',
    live_refresh: 'Aktualisieren',
    live_empty_title: 'Keine Streams verfugbar',
    live_empty_desc: 'Parkkameras erscheinen hier, wenn sie live sind.',
    live_failed_load: 'Streams konnten nicht geladen werden',
    live_failed_join: 'Beitritt zum Stream fehlgeschlagen',
    attraction_loading: 'Attraktionsdetails werden geladen...',
    attraction_unavailable: 'Attraktion nicht verfugbar',
    attraction_not_found: 'Diese Attraktion wurde nicht gefunden.',
    attraction_back_to_list: 'Zuruck zu Attraktionen',
    attraction_discover_copy: 'Entdecken Sie dieses kenianische Reiseziel.',
    attraction_resident_fee: 'Gebuhr fur Einheimische',
    attraction_nonresident_fee: 'Gebuhr fur Auslander',
    attraction_quick_actions: 'Schnellaktionen',
    attraction_book_now: 'Jetzt buchen',
    attraction_book_copy: 'Offnen Sie die Buchung fur diese Attraktion.',
    attraction_go_live: 'Live gehen',
    attraction_go_live_copy: 'Starten oder verwalten Sie einen Livestream fur diese Attraktion.',
    attraction_gps_navigation: 'GPS-Navigation',
    attraction_gps_missing: 'GPS-Koordinaten sind fur diese Attraktion noch nicht verfugbar.',
    attraction_gps_copy: 'Offnen Sie die Turn-by-Turn-Navigation zu dieser Attraktion.',
    attraction_location: 'Standort',
    attraction_coords_missing: 'Koordinaten wurden fur diese Attraktion noch nicht hinzugefugt.',
    checkout_title: 'Buchungs-Checkout',
    checkout_subtitle: 'Wahlen Sie Ihre Zahlungsmethode und bestatigen Sie danach Ihre Reservierungsdetails.',
    checkout_phone_required: 'Telefon erforderlich',
    checkout_phone_required_copy: 'Geben Sie die Telefonnummer fur diese Buchung ein.',
    checkout_missing_details: 'Fehlende Angaben',
    checkout_missing_card: 'Bitte alle Kartendaten ausfullen.',
    checkout_invalid_card: 'Ungultige Karte',
    checkout_invalid_card_copy: 'Bitte eine gultige Kartennummer eingeben.',
    checkout_mpesa_sent: 'M-Pesa-Anfrage gesendet',
    checkout_payment_success: 'Zahlung erfolgreich',
    checkout_payment_failed: 'Zahlung fehlgeschlagen',
    checkout_check_phone: 'Prufen Sie Ihr Telefon auf die M-Pesa-STK-Anfrage.',
    checkout_card_success: 'Ihre Kartenzahlung und Buchung wurden abgeschlossen.',
    checkout_back: 'Zuruck',
    checkout_complete_booking: 'SchlieBen Sie Ihre Buchung ab fur',
    checkout_summary_package: 'Paket',
    checkout_summary_date: 'Reisedatum',
    checkout_summary_participants: 'Teilnehmer',
    checkout_payment_method: 'Zahlungsmethode',
    checkout_method_mpesa: 'M-Pesa',
    checkout_method_mpesa_copy: 'Produktionsreifer STK-Push-Ablauf',
    checkout_method_card: 'Karte',
    checkout_method_card_copy: 'Sofortige Reservierungsbestatigung',
    checkout_phone_placeholder: 'M-Pesa- / Buchungstelefonnummer',
    checkout_mpesa_title: 'M-Pesa STK Push',
    checkout_mpesa_notice: 'Verwenden Sie eine gultige Safaricom-Nummer im Format 07XXXXXXXX, 2547XXXXXXXX oder +2547XXXXXXXX.',
    checkout_card_details: 'Kartendetails',
    checkout_cardholder_name: 'Name auf der Karte',
    checkout_card_number: 'Kartennummer',
    checkout_expiry: 'MM/JJ',
    checkout_cvv: 'CVV',
    checkout_sending_mpesa: 'M-Pesa-Anfrage wird gesendet...',
    checkout_processing_payment: 'Zahlung wird verarbeitet...',
    checkout_pay_mpesa: 'Mit M-Pesa bezahlen',
    checkout_pay_card: 'Mit Karte bezahlen',
    map_location_settings: 'Aktivieren Sie die Standortdienste fur die In-App-Navigation.',
    map_permission_required: 'Standortberechtigung ist fur die Navigation erforderlich.',
    map_unavailable: 'Karte nicht verfugbar',
    map_load_failed: 'Kartendaten konnten nicht geladen werden.',
    map_directions_unavailable: 'Navigation nicht verfugbar',
    map_no_coords: 'Keine Koordinaten fur diese Attraktion gefunden.',
    map_open_failed: 'Navigation konnte auf diesem Gerat nicht geoffnet werden.',
    map_no_route: 'Fur dieses Ziel konnte keine Route erstellt werden.',
    map_loading_title: 'Karte wird geladen',
    map_loading_copy: 'Ziel- und GPS-Daten werden vorbereitet.',
    map_header_subtitle: 'In-App-GPS mit Live-Route, Entfernung und nachstem Schritt.',
    map_nav_title: 'Turn-by-Turn-Navigation',
    map_remaining: 'Verbleibend',
    map_eta: 'Ankunft',
    map_next_instruction: 'Nachste Anweisung',
    map_arrived: 'Sie sind fast am Ziel angekommen.',
    map_route_appears: 'Die Routenhinweise erscheinen, sobald die Route geladen ist.',
    map_destination_label: 'Ziel',
    map_coords_missing: 'Koordinaten sind fur diese Attraktion noch nicht verfugbar.',
    map_refresh_route: 'In-App-Route aktualisieren',
    map_open_google: 'In Google Maps offnen',
    map_using_last_known: 'Ihr letzter bekannter Standort wird angezeigt, bis GPS verfugbar ist.',
    map_instruction_start: 'Starten Sie auf Ihrer Route.',
    map_instruction_follow_road: 'Folgen Sie der Route uber',
    map_instruction_follow_route: 'Folgen Sie der Route weiter.',
    map_instruction_arrive: 'Sie sind kurz vor Ihrem Ziel.',
    map_step_in: 'In',
    broadcast_start_failed: 'Stream konnte nicht gestartet werden',
    broadcast_camera_broadcasting: 'Kamera sendet',
    broadcast_camera_ready: 'Kamera bereit',
    broadcast_tap_start: 'Tippen Sie auf Start, um live zu gehen',
    broadcast_live: 'LIVE',
    broadcast_park_camera: 'Parkkamera',
    broadcast_ready_status: 'Bereit zum Streamen',
    broadcast_go_live: 'Live gehen',
    broadcast_stop_stream: 'Stream stoppen',
    broadcast_stop_title: 'Streaming stoppen?',
    broadcast_stop_copy: 'Dadurch wird der Livestream fur alle Zuschauer beendet.',
    broadcast_gps_navigation: 'GPS-Navigation',
    navigation_permission_denied: 'Berechtigung verweigert',
    navigation_permission_required: 'Standortzugriff ist fur die Navigation erforderlich.',
    navigation_error: 'Navigation konnte nicht gestartet werden. Bitte erneut versuchen.',
    navigation_loading: 'Navigation wird geladen...',
    navigation_live: 'Live-Navigation',
    navigation_distance: 'Entfernung',
    navigation_navigate_to: 'Navigieren zu',
  },
  zh: {
    home: '首页',
    explore: '景点',
    bookings: '预订',
    chatbot: '助手',
    profile: '个人资料',
    live: '直播',
    login_title: '欢迎回来',
    login_copy: '登录以继续规划您的下一次肯尼亚之旅。',
    register_title: '创建账号',
    register_copy: '加入 Explore Kenya 来管理旅行和预订。',
    forgot_title: '重置密码',
    forgot_copy: '输入您的邮箱以生成安全重置码。',
    reset_title: '输入重置码',
    reset_copy: '使用重置码并设置新密码。',
    full_name: '姓名',
    phone_number: '电话号码',
    register: '注册',
    login: '登录',
    forgot_password: '忘记密码？',
    no_account: '没有账号？注册',
    already_have_account: '已有账号？登录',
    language: '语言',
    interests: '旅行兴趣',
    save_profile: '保存资料',
    logout: '退出登录',
    profile_title: '个人资料管理',
    profile_copy: '更新账户信息、兴趣和首选语言。',
    settings: '设置',
    language_saved: '语言已更新。',
    profile_saved: '您的资料已成功更新。',
    loading: '加载中...',
    language_english: '英语',
    language_swahili: '斯瓦希里语',
    language_french: '法语',
    language_spanish: '西班牙语',
    language_german: '德语',
    language_chinese: '中文',
    language_arabic: '阿拉伯语',
    landing_badge: '野生动物和旅游景点',
    landing_title: '发现肯尼亚的魅力',
    landing_copy: '体验精彩的野生动物、丰富的文化和难忘的冒险。',
    landing_explore: '探索目的地',
    landing_watch_live: '观看直播',
    landing_stat_parks: '公园和保护区',
    landing_stat_visitors: '月访客',
    landing_stat_rating: '应用评分',
    landing_ready_label: '准备探索',
    landing_ready_title: '发现肯尼亚景点',
    landing_ready_copy: '超过 20 个公园、保护区和海滩，提供完整筛选和地图。',
    landing_explore_title: '探索所有景点',
    landing_explore_copy: '肯尼亚超过 20 个公园、保护区和海滩',
    landing_feature_navigation_title: 'GPS 导航',
    landing_feature_navigation_copy: '前往每个景点的实时地图。',
    landing_feature_mpesa_title: 'M-Pesa 预订',
    landing_feature_mpesa_copy: '通过 M-Pesa STK push 即时付款。',
    landing_feature_live_title: '实时直播',
    landing_feature_live_copy: '从任何公园观看野生动物直播。',
    landing_feature_language_title: '语言支持',
    landing_feature_language_copy: '应用全面支持主要游客语言。',
    landing_booking_title: '快速预订',
    landing_booking_cta: '开始',
    landing_footer_about: '关于',
    landing_footer_live: '直播摄像头',
    landing_footer_bookings: '预订',
    broadcast_viewers_watching: '正在观看',
    broadcast_you_are_live: '你正在直播',
    navigation_you_are_here: '你在这里',
    navigation_your_destination: '你的目的地',
    navigation_map_error: '地图错误',
    catalog_greeting: '早上好',
    catalog_search_placeholder: '搜索景点...',
    catalog_view_more: '查看',
    catalog_empty: '未找到景点。',
    catalog_bookings: '预订',
    category_all: '全部',
    category_wildlife: '野生动物',
    category_culture: '文化',
    category_cultural: '文化类',
    category_adventure: '冒险',
    category_beach: '海滩',
    category_history: '历史',
    category_historical: '历史类',
    auth_phone_placeholder: '07XX XXX XXX',
    chatbot_no_response: '暂无回复。',
    chatbot_unavailable: '助手当前无法回答。',
    map_using_last_known: '在 GPS 可用之前，将显示你最后已知的位置。',
    map_instruction_start: '开始你的路线。',
    map_instruction_follow_road: '沿此道路继续',
    map_instruction_follow_route: '继续沿路线前进。',
    map_instruction_arrive: '你即将到达目的地。',
    map_step_in: '在',
  },
  ar: {
    home: 'الرئيسية',
    explore: 'المعالم',
    bookings: 'الحجوزات',
    chatbot: 'المساعد',
    profile: 'الملف الشخصي',
    live: 'مباشر',
    login_title: 'مرحبا بعودتك',
    login_copy: 'سجل الدخول لمتابعة التخطيط لمغامرتك القادمة في كينيا.',
    register_title: 'انشئ حسابك',
    register_copy: 'انضم الى Explore Kenya لادارة الرحلات والحجوزات.',
    forgot_title: 'اعادة تعيين كلمة المرور',
    forgot_copy: 'ادخل بريدك الالكتروني للحصول على رمز آمن.',
    reset_title: 'ادخل رمز اعادة التعيين',
    reset_copy: 'استخدم الرمز واختر كلمة مرور جديدة.',
    full_name: 'الاسم الكامل',
    phone_number: 'رقم الهاتف',
    register: 'تسجيل',
    login: 'تسجيل الدخول',
    forgot_password: 'هل نسيت كلمة المرور؟',
    no_account: 'ليس لديك حساب؟ سجل',
    already_have_account: 'لديك حساب بالفعل؟ سجل الدخول',
    language: 'اللغة',
    interests: 'اهتمامات السفر',
    save_profile: 'حفظ الملف الشخصي',
    logout: 'تسجيل الخروج',
    profile_title: 'ادارة الملف الشخصي',
    profile_copy: 'حدث حسابك واهتماماتك ولغة التطبيق المفضلة.',
    settings: 'الاعدادات',
    language_saved: 'تم تحديث اللغة.',
    profile_saved: 'تم تحديث ملفك الشخصي بنجاح.',
    loading: 'جار التحميل...',
    language_english: 'الانجليزية',
    language_swahili: 'السواحيلية',
    language_french: 'الفرنسية',
    language_spanish: 'الاسبانية',
    language_german: 'الالمانية',
    language_chinese: 'الصينية',
    language_arabic: 'العربية',
    landing_badge: 'الحياة البرية والمعالم السياحية',
    landing_title: 'اكتشف سحر كينيا',
    landing_copy: 'استمتع بالحياة البرية المذهلة والثقافة الغنية والمغامرات التي لا تنسى.',
    landing_explore: 'استكشف الوجهات',
    landing_watch_live: 'شاهد المباشر',
    landing_stat_parks: 'المتنزهات والمحميات',
    landing_stat_visitors: 'الزوار شهريا',
    landing_stat_rating: 'تقييم التطبيق',
    landing_ready_label: 'جاهز للاستكشاف',
    landing_ready_title: 'اكتشف معالم كينيا',
    landing_ready_copy: 'اكثر من 20 متنزها ومحميّة وشاطئا مع خرائط وفلاتر كاملة.',
    landing_explore_title: 'استكشف كل المعالم',
    landing_explore_copy: 'اكثر من 20 متنزها ومحميّة وشاطئا في كينيا',
    landing_feature_navigation_title: 'ملاحة GPS',
    landing_feature_navigation_copy: 'خرائط فورية لكل معلم.',
    landing_feature_mpesa_title: 'حجز M-Pesa',
    landing_feature_mpesa_copy: 'ادفع فورا عبر M-Pesa STK push.',
    landing_feature_live_title: 'بث مباشر',
    landing_feature_live_copy: 'شاهد الحياة البرية مباشرة من اي متنزه.',
    landing_feature_language_title: 'دعم اللغات',
    landing_feature_language_copy: 'دعم كامل للغات الرئيسية المستخدمة من قبل السياح.',
    landing_booking_title: 'حجز سريع',
    landing_booking_cta: 'ابدأ',
    landing_footer_about: 'حول',
    landing_footer_live: 'كاميرات مباشرة',
    landing_footer_bookings: 'الحجوزات',
    broadcast_viewers_watching: 'يشاهدون',
    broadcast_you_are_live: 'أنت على الهواء',
    navigation_you_are_here: 'أنت هنا',
    navigation_your_destination: 'وجهتك',
    navigation_map_error: 'خطأ في الخريطة',
    catalog_greeting: 'صباح الخير',
    catalog_search_placeholder: 'ابحث عن المعالم...',
    catalog_view_more: 'عرض',
    catalog_empty: 'لم يتم العثور على معالم.',
    catalog_bookings: 'الحجوزات',
    category_all: 'الكل',
    category_wildlife: 'الحياة البرية',
    category_culture: 'الثقافة',
    category_cultural: 'ثقافي',
    category_adventure: 'مغامرة',
    category_beach: 'شاطئ',
    category_history: 'التاريخ',
    category_historical: 'تاريخي',
    auth_phone_placeholder: '07XX XXX XXX',
    chatbot_no_response: 'لا توجد استجابة متاحة.',
    chatbot_unavailable: 'لا يستطيع المساعد الرد حاليا.',
    map_using_last_known: 'يتم عرض آخر موقع معروف لك حتى يصبح GPS متاحا.',
    map_instruction_start: 'ابدأ مسارك.',
    map_instruction_follow_road: 'اتبع الطريق عبر',
    map_instruction_follow_route: 'واصل السير على المسار.',
    map_instruction_arrive: 'أنت على وشك الوصول إلى وجهتك.',
    map_step_in: 'خلال',
  },
};

const LocalizationContext = createContext(null);

export function LocalizationProvider({ children }) {
  const [language, setLanguageState] = useState('en');
  const [ready, setReady] = useState(false);

  useEffect(() => {
    const loadLanguage = async () => {
      try {
        const savedLanguage = await SecureStore.getItemAsync(LANGUAGE_KEY);
        if (savedLanguage && translations[savedLanguage]) {
          setLanguageState(savedLanguage);
        }
      } finally {
        setReady(true);
      }
    };

    void loadLanguage();
  }, []);

  const setLanguage = async (nextLanguage) => {
    if (!translations[nextLanguage]) {
      return;
    }

    setLanguageState(nextLanguage);
    await SecureStore.setItemAsync(LANGUAGE_KEY, nextLanguage);
  };

  const value = useMemo(
    () => ({
      language,
      setLanguage,
      ready,
      t: (key) => translations[language]?.[key] || translations.en[key] || key,
    }),
    [language, ready]
  );

  return <LocalizationContext.Provider value={value}>{children}</LocalizationContext.Provider>;
}

export function useLocale() {
  const context = useContext(LocalizationContext);
  if (!context) {
    throw new Error('useLocale must be used within LocalizationProvider');
  }

  return context;
}
